# -*- coding: utf-8 -*-
"""mall_customers_cleaning

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YvNGbujvufHwYho4NEDPxqzatgQohrMA
"""

import pandas as pd

# Load the CSV file
df = pd.read_csv("/content/Mall_Customers.csv")

# Convert headers to lowercase, replace spaces with underscores, and remove symbols
df.columns = [col.lower().strip().replace(" ", "_").replace("(", "").replace(")", "") for col in df.columns]

# Drop any exact duplicate rows (if any)
df = df.drop_duplicates()

print("Duplicates Removed:", df.duplicated().sum())

# Ensure correct datatypes
df['age'] = df['age'].astype(int)
df['annual_income_k$'] = df['annual_income_k$'].astype(int)
df['spending_score_1-100'] = df['spending_score_1-100'].astype(int)

# Save the cleaned dataset
df.to_csv("Mall_Customers_Cleaned.csv", index=False)